export const SITE_CONFIG = {
  name: "MITANSH TOUR & TRAVELS",
  tagline: "Premium Taxi & Tour Services",
  description: "Premium taxi and tour services in Mathura, Vrindavan & Agra. 24×7 airport transfers, temple tours, outstation taxi with professional drivers and transparent pricing.",
  url: "https://mitanshtourtravels.com",
  ogImage: "/og-image.jpg",
  links: {
    twitter: "https://twitter.com/mitanshtours",
    facebook: "https://facebook.com/mitanshtourtravels",
    instagram: "https://instagram.com/mitanshtourtravels",
    linkedin: "https://linkedin.com/company/mitanshtourtravels",
  },
  contact: {
    phone: "+91 9027264612",
    phoneAlt: "+91 8534829750",
    email: "mitanshtravels.office@gmail.com",
    whatsapp: "+91 9027264612",
    whatsappClean: "919027264612",
    address: "Nikunj Vatika, Gauduli Puram, Vrindavan, Uttar Pradesh, India",
    owners: ["Jitendra Kumar", "Himanshu Kumar"],
  },
  contactLinks: {
    tel: "tel:+91 9027264612",
    telAlt: "tel:+91 8534829750",
    mailto: "mailto:mitanshtravels.office@gmail.com",
    whatsapp: "https://wa.me/919027264612",
    whatsappWithMessage: "https://wa.me/919027264612?text=" + encodeURIComponent("🙏 राधे राधे | Radhe Radhe 🙏\n\nThank you for your enquiry!\n\nधन्यवाद आपकी पूछताछ के लिए!\n\nMITANSH TOUR & TRAVELS\nमितांश टूर एंड ट्रैवल्स\n\nMathura | Vrindavan | Agra"),
  },
  cities: [
    "Mathura",
    "Vrindavan",
    "Agra",
    "Delhi",
    "Noida",
    "Greater Noida",
    "Gurugram",
    "Jaipur",
    "Lucknow",
  ],
};

export const FLEET = [
  {
    id: "swift-dzire",
    name: "Swift Dzire",
    category: "Sedan",
    image: "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=800",
    seats: 4,
    luggage: 2,
    ac: true,
    fuel: "Petrol/CNG",
    pricePerKm: 12,
    features: ["GPS Navigation", "USB Charging", "Water Bottles", "Newspapers"],
  },
  {
    id: "maruti-ertiga",
    name: "Maruti Ertiga",
    category: "SUV",
    image: "https://images.unsplash.com/photo-1550355291-bbee04a92027?w=800",
    seats: 6,
    luggage: 3,
    ac: true,
    fuel: "Petrol/Diesel",
    pricePerKm: 14,
    features: ["GPS Navigation", "USB Charging", "Water Bottles", "Spacious"],
  },
  {
    id: "toyota-innova",
    name: "Toyota Innova",
    category: "SUV",
    image: "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=800",
    seats: 7,
    luggage: 4,
    ac: true,
    fuel: "Diesel",
    pricePerKm: 16,
    features: ["GPS Navigation", "USB Charging", "Water Bottles", "Premium Comfort"],
  },
  {
    id: "toyota-innova-crysta",
    name: "Toyota Innova Crysta",
    category: "Premium SUV",
    image: "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=800",
    seats: 7,
    luggage: 4,
    ac: true,
    fuel: "Diesel",
    pricePerKm: 18,
    features: ["GPS Navigation", "USB Charging", "Water Bottles", "Leather Seats", "Pushback"],
  },
  {
    id: "tempo-traveller",
    name: "Tempo Traveller",
    category: "Minibus",
    image: "https://images.unsplash.com/photo-1570125909232-eb263c188f7e?w=800",
    seats: 12,
    luggage: 8,
    ac: true,
    fuel: "Diesel",
    pricePerKm: 25,
    features: ["GPS Navigation", "USB Charging", "Water Bottles", "Pushback Seats", "Music System"],
  },
  {
    id: "luxury-sedan",
    name: "Luxury Sedan",
    category: "Premium Sedan",
    image: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800",
    seats: 4,
    luggage: 2,
    ac: true,
    fuel: "Petrol",
    pricePerKm: 20,
    features: ["GPS Navigation", "USB Charging", "Water Bottles", "Leather Seats", "Premium Service"],
  },
];

export const TOUR_PACKAGES = [
  {
    id: "brij-darshan",
    name: "Brij Darshan",
    duration: "2 Days",
    price: 8500,
    image: "https://images.unsplash.com/photo-1564399580075-5dfe19c205f3?w=800",
    description: "Complete pilgrimage tour of all major temples in Braj region including Mathura, Vrindavan, Govardhan, Barsana, Gokul, and Nandgaon.",
    highlights: ["Mathura Temples", "Vrindavan Temples", "Govardhan Parikrama", "Barsana & Nandgaon", "All Meals Included"],
    includes: ["AC Vehicle", "Driver Allowance", "Toll & Parking", "Guide Service", "Breakfast & Dinner"],
  },
  {
    id: "mathura-local",
    name: "Mathura Local",
    duration: "1 Day",
    price: 3500,
    image: "https://images.unsplash.com/photo-1564399580075-5dfe19c205f3?w=800",
    description: "Explore the birthplace of Lord Krishna. Visit Krishna Janmasthan Temple, Dwarkadheesh Temple, Vishram Ghat, and other sacred sites.",
    highlights: ["Krishna Janmasthan", "Dwarkadheesh Temple", "Vishram Ghat", "Potara Kund", "Local Sightseeing"],
    includes: ["AC Vehicle", "Driver Allowance", "Toll & Parking", "Guide Service"],
  },
  {
    id: "vrindavan-local",
    name: "Vrindavan Local",
    duration: "1 Day",
    price: 3500,
    image: "https://images.unsplash.com/photo-1564399580075-5dfe19c205f3?w=800",
    description: "Experience the divine atmosphere of Vrindavan with visits to Banke Bihari Temple, ISKCON Temple, Prem Mandir, and Radha Vallabh Temple.",
    highlights: ["Banke Bihari Temple", "ISKCON Temple", "Prem Mandir", "Radha Vallabh Temple", "Yamuna Arti"],
    includes: ["AC Vehicle", "Driver Allowance", "Toll & Parking", "Guide Service"],
  },
  {
    id: "govardhan",
    name: "Govardhan",
    duration: "1 Day",
    price: 4000,
    image: "https://images.unsplash.com/photo-1564399580075-5dfe19c205f3?w=800",
    description: "Complete Govardhan Parikrama covering all important temples including Govardhan Hill, Daan Ghati, and Mukharvind.",
    highlights: ["Govardhan Hill", "Daan Ghati Temple", "Mukharvind", "Kusum Sarovar", "Parikrama"],
    includes: ["AC Vehicle", "Driver Allowance", "Toll & Parking", "Guide Service"],
  },
  {
    id: "barsana",
    name: "Barsana",
    duration: "1 Day",
    price: 4500,
    image: "https://images.unsplash.com/photo-1564399580075-5dfe19c205f3?w=800",
    description: "Visit the birthplace of Radha Rani. Explore Barsana's beautiful temples and experience the divine love of Radha-Krishna.",
    highlights: ["Radha Rani Temple", "Maan Mandir", "Mor Kutir", "Rangeeli Mahal", "Village Tour"],
    includes: ["AC Vehicle", "Driver Allowance", "Toll & Parking", "Guide Service"],
  },
  {
    id: "gokul",
    name: "Gokul",
    duration: "1 Day",
    price: 4000,
    image: "https://images.unsplash.com/photo-1564399580075-5dfe19c205f3?w=800",
    description: "Where Lord Krishna spent his childhood. Visit Gokul's ancient temples and experience the pastoral charm of Krishna's early life.",
    highlights: ["Gokulnath Temple", "Raman Reti", "Thakurani Ghat", "Brahma Ghat", "Childhood Sites"],
    includes: ["AC Vehicle", "Driver Allowance", "Toll & Parking", "Guide Service"],
  },
  {
    id: "nandgaon",
    name: "Nandgaon",
    duration: "1 Day",
    price: 4500,
    image: "https://images.unsplash.com/photo-1564399580075-5dfe19c205f3?w=800",
    description: "Home of Nanda Baba, Krishna's foster father. Visit the beautiful hilltop temple and experience the divine atmosphere.",
    highlights: ["Nand Bhavan", "Pan Sarovar", "Yashoda Nandan Temple", "Hilltop View", "Village Experience"],
    includes: ["AC Vehicle", "Driver Allowance", "Toll & Parking", "Guide Service"],
  },
  {
    id: "agra-tour",
    name: "Agra Tour",
    duration: "1 Day",
    price: 5000,
    image: "https://images.unsplash.com/photo-1564507592333-c60657eea523?w=800",
    description: "Visit the magnificent Taj Mahal, Agra Fort, and other Mughal-era monuments. A perfect day trip from Mathura/Vrindavan.",
    highlights: ["Taj Mahal", "Agra Fort", "Fatehpur Sikri", "Mehtab Bagh", "Local Shopping"],
    includes: ["AC Vehicle", "Driver Allowance", "Toll & Parking", "Guide Service", "Monument Tickets"],
  },
  {
    id: "taj-mahal-tour",
    name: "Taj Mahal Tour",
    duration: "1 Day",
    price: 5500,
    image: "https://images.unsplash.com/photo-1564507592333-c60657eea523?w=800",
    description: "Sunrise tour of the Taj Mahal with professional guide. Experience the monument at its most magical time.",
    highlights: ["Sunrise at Taj", "Professional Guide", "Agra Fort", "Mehtab Bagh", "Photography Tour"],
    includes: ["AC Vehicle", "Driver Allowance", "Toll & Parking", "Expert Guide", "Monument Tickets", "Breakfast"],
  },
  {
    id: "weekend-package",
    name: "Weekend Package",
    duration: "2 Days",
    price: 12000,
    image: "https://images.unsplash.com/photo-1564399580075-5dfe19c205f3?w=800",
    description: "Perfect weekend getaway covering Mathura, Vrindavan, and Agra. Experience the best of Braj region in two days.",
    highlights: ["Mathura Temples", "Vrindavan Temples", "Taj Mahal", "Agra Fort", "All Meals Included"],
    includes: ["AC Vehicle", "Driver Allowance", "Toll & Parking", "Guide Service", "Hotel Stay", "All Meals"],
  },
  {
    id: "vip-darshan",
    name: "VIP Darshan",
    duration: "1 Day",
    price: 8000,
    image: "https://images.unsplash.com/photo-1564399580075-5dfe19c205f3?w=800",
    description: "Exclusive VIP darshan package with special access to major temples. Priority entry and personalized service.",
    highlights: ["VIP Entry", "Priority Darshan", "Personal Guide", "Luxury Vehicle", "Special Prasad"],
    includes: ["Luxury Vehicle", "Driver Allowance", "Toll & Parking", "VIP Guide", "Special Entry Fees", "Refreshments"],
  },
  {
    id: "family-package",
    name: "Family Package",
    duration: "3 Days",
    price: 18000,
    image: "https://images.unsplash.com/photo-1564399580075-5dfe19c205f3?w=800",
    description: "Complete family pilgrimage package covering all major destinations. Comfortable travel with family-friendly accommodations.",
    highlights: ["All Major Temples", "Family Hotel", "All Meals", "Child-Friendly Guide", "Shopping Time"],
    includes: ["AC Vehicle", "Driver Allowance", "Toll & Parking", "Family Guide", "Hotel Stay", "All Meals", "Shopping Assistance"],
  },
];

export const POPULAR_ROUTES = [
  {
    id: "delhi-to-vrindavan",
    from: "Delhi",
    to: "Vrindavan",
    distance: 180,
    duration: "4-5 hours",
    price: 3500,
    description: "Comfortable taxi service from Delhi to Vrindavan. Perfect for pilgrims and tourists visiting the holy city.",
    popular: true,
  },
  {
    id: "delhi-airport-to-vrindavan",
    from: "Delhi Airport",
    to: "Vrindavan",
    distance: 190,
    duration: "4-5 hours",
    price: 4000,
    description: "Airport pickup and drop service from IGI Delhi Airport to Vrindavan. Meet and greet service included.",
    popular: true,
  },
  {
    id: "agra-to-mathura",
    from: "Agra",
    to: "Mathura",
    distance: 58,
    duration: "1.5 hours",
    price: 1500,
    description: "Quick and comfortable taxi service between Agra and Mathura. Ideal for Taj Mahal visitors extending to Mathura.",
    popular: true,
  },
  {
    id: "jaipur-to-vrindavan",
    from: "Jaipur",
    to: "Vrindavan",
    distance: 240,
    duration: "5-6 hours",
    price: 5500,
    description: "Premium taxi service from Jaipur to Vrindavan. Comfortable journey through Rajasthan to Uttar Pradesh.",
    popular: false,
  },
  {
    id: "noida-to-mathura",
    from: "Noida",
    to: "Mathura",
    distance: 150,
    duration: "3-4 hours",
    price: 3000,
    description: "Reliable taxi service from Noida to Mathura. Perfect for weekend pilgrimages and business trips.",
    popular: true,
  },
  {
    id: "lucknow-to-vrindavan",
    from: "Lucknow",
    to: "Vrindavan",
    distance: 380,
    duration: "7-8 hours",
    price: 8500,
    description: "Long-distance taxi service from Lucknow to Vrindavan. Comfortable travel with experienced drivers.",
    popular: false,
  },
  {
    id: "gurugram-to-mathura",
    from: "Gurugram",
    to: "Mathura",
    distance: 170,
    duration: "4 hours",
    price: 3200,
    description: "Premium taxi service from Gurugram to Mathura. Ideal for corporate travelers and pilgrims.",
    popular: false,
  },
  {
    id: "greater-noida-to-vrindavan",
    from: "Greater Noida",
    to: "Vrindavan",
    distance: 140,
    duration: "3-4 hours",
    price: 2800,
    description: "Affordable taxi service from Greater Noida to Vrindavan. Quick and comfortable journey.",
    popular: false,
  },
];

export const SERVICES = [
  {
    id: "airport-taxi",
    name: "Airport Taxi",
    icon: "Plane",
    description: "24×7 airport transfer service to and from Delhi, Agra, and Jaipur airports. Meet and greet service included.",
    features: ["Meet & Greet", "Flight Tracking", "Luggage Assistance", "Waiting Time Included"],
  },
  {
    id: "local-taxi",
    name: "Local Taxi",
    icon: "Car",
    description: "Local sightseeing taxi service in Mathura, Vrindavan, and Agra. Hourly and daily packages available.",
    features: ["Hourly Packages", "Local Knowledge", "Flexible Timing", "Multiple Stops"],
  },
  {
    id: "outstation-taxi",
    name: "Outstation Taxi",
    icon: "MapPin",
    description: "One-way and round-trip taxi service to all major cities inUP, Rajasthan, and Delhi NCR.",
    features: ["One-way Trips", "Round-trip Packages", "Inter-city Travel", "Transparent Pricing"],
  },
  {
    id: "corporate-taxi",
    name: "Corporate Taxi",
    icon: "Briefcase",
    description: "Premium corporate travel solutions for businesses. Monthly contracts and employee transportation services.",
    features: ["Monthly Contracts", "Billing Solutions", "Professional Drivers", "Luxury Fleet"],
  },
  {
    id: "wedding-taxi",
    name: "Wedding Taxi",
    icon: "Heart",
    description: "Special wedding transportation for bride, groom, and guests. Decorated vehicles and special packages.",
    features: ["Decorated Vehicles", "Guest Transportation", "Baraat Service", "Special Packages"],
  },
  {
    id: "tempo-traveller",
    name: "Tempo Traveller",
    icon: "Users",
    description: "Group travel solution with tempo traveller. Perfect for family tours, pilgrimages, and corporate outings.",
    features: ["9-26 Seater", "Pushback Seats", "AC/Non-AC Options", "Group Discounts"],
  },
];

export const TESTIMONIALS = [
  {
    id: 1,
    name: "Rajesh Sharma",
    location: "Delhi",
    rating: 5,
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100",
    review: "Excellent service from Delhi to Vrindavan. Driver was very professional and knowledgeable about the route. Vehicle was clean and comfortable. Highly recommended!",
    date: "2024-01-15",
  },
  {
    id: 2,
    name: "Priya Gupta",
    location: "Mumbai",
    rating: 5,
    image: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100",
    review: "Used their service for Mathura-Vrindavan tour. The Brij Darshan package was well organized. Guide was excellent and driver was very cooperative. Will book again!",
    date: "2024-01-10",
  },
  {
    id: 3,
    name: "Amit Verma",
    location: "Lucknow",
    rating: 5,
    image: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100",
    review: "Booked tempo traveller for family pilgrimage from Lucknow to Vrindavan. Very comfortable journey. Driver was experienced and safe. Great value for money.",
    date: "2024-01-05",
  },
  {
    id: 4,
    name: "Sneha Patel",
    location: "Ahmedabad",
    rating: 5,
    image: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100",
    review: "Airport pickup from Delhi to Vrindavan was seamless. Driver was waiting at arrival with name board. Very punctual and professional service.",
    date: "2023-12-28",
  },
  {
    id: 5,
    name: "Vikram Singh",
    location: "Jaipur",
    rating: 5,
    image: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100",
    review: "Outstation taxi from Jaipur to Vrindavan for weekend trip. Transparent pricing with no hidden charges. Vehicle was in excellent condition. Great experience!",
    date: "2023-12-20",
  },
  {
    id: 6,
    name: "Meera Krishnan",
    location: "Chennai",
    rating: 5,
    image: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100",
    review: "VIP Darshan package was worth every rupee. Special entry to temples saved so much time. Guide was very knowledgeable about the spiritual significance. Divine experience!",
    date: "2023-12-15",
  },
];

export const FAQS = [
  {
    id: 1,
    question: "How do I book a taxi with Mitansh Tour & Travels?",
    answer: "You can book a taxi through our website by filling the booking form, calling us at +91 9027264612, or sending a WhatsApp message. We offer instant booking confirmation and 24×7 customer support.",
    category: "Booking",
  },
  {
    id: 2,
    question: "What are your payment options?",
    answer: "We accept multiple payment options including cash, UPI, bank transfer, and online payment. For advance booking, we require a 20% advance payment and the remaining amount can be paid to the driver or online after the trip.",
    category: "Payment",
  },
  {
    id: 3,
    question: "Do you provide airport pickup and drop service?",
    answer: "Yes, we provide 24×7 airport transfer service to and from Delhi IGI Airport, Agra Airport, and Jaipur Airport. Our drivers track flight status and wait for delayed flights at no extra cost.",
    category: "Services",
  },
  {
    id: 4,
    question: "What is included in the tour package price?",
    answer: "Our tour packages include AC vehicle, driver allowance, toll tax, parking fees, and guide service (where specified). Some premium packages also include meals and hotel accommodation. Check individual package details for complete inclusions.",
    category: "Packages",
  },
  {
    id: 5,
    question: "Can I customize my tour package?",
    answer: "Absolutely! We offer fully customizable tour packages. You can modify the itinerary, add or remove destinations, choose your preferred vehicle, and adjust the duration. Contact us with your requirements and we'll create a personalized package for you.",
    category: "Packages",
  },
  {
    id: 6,
    question: "What types of vehicles do you have?",
    answer: "We have a diverse fleet including Swift Dzire (sedan), Maruti Ertiga (SUV), Toyota Innova, Toyota Innova Crysta, Tempo Traveller (9-26 seater), and luxury sedans. All vehicles are well-maintained, air-conditioned, and regularly serviced.",
    category: "Fleet",
  },
  {
    id: 7,
    question: "Are your drivers experienced and licensed?",
    answer: "Yes, all our drivers are licensed, experienced, and background-verified. They have excellent knowledge of local routes, tourist destinations, and are trained in customer service. Many of our drivers have been with us for 5+ years.",
    category: "Services",
  },
  {
    id: 8,
    question: "Do you provide one-way taxi service?",
    answer: "Yes, we offer one-way taxi service to all major cities. You only pay for the distance traveled one way. This is cost-effective for travelers who don't require return travel with the same vehicle.",
    category: "Services",
  },
  {
    id: 9,
    question: "What is your cancellation policy?",
    answer: "Free cancellation up to 24 hours before the scheduled trip. 50% refund for cancellations made 12-24 hours before. No refund for cancellations within 12 hours of trip start time. In case of emergencies, we may consider exceptions on a case-by-case basis.",
    category: "Booking",
  },
  {
    id: 10,
    question: "Do you provide taxi service for weddings?",
    answer: "Yes, we offer special wedding taxi services including decorated vehicles for bride and groom, guest transportation, baraat service, and multi-vehicle coordination. We can arrange the entire wedding transportation logistics.",
    category: "Services",
  },
  {
    id: 11,
    question: "What are your operating hours?",
    answer: "We operate 24×7, 365 days a year. You can book our services at any time, and our customer support is available round the clock for assistance and bookings.",
    category: "General",
  },
  {
    id: 12,
    question: "Do you provide corporate taxi services?",
    answer: "Yes, we have dedicated corporate travel solutions including employee transportation, client pickup/drop, monthly contracts, and billing solutions. We offer special corporate rates and priority service for business clients.",
    category: "Services",
  },
  {
    id: 13,
    question: "Is there any waiting charge if the trip gets delayed?",
    answer: "For local trips, the first 30 minutes of waiting is free. After that, nominal waiting charges apply. For outstation trips, we include reasonable waiting time in the package. Extended delays due to traffic or client requirements are charged at hourly rates.",
    category: "Pricing",
  },
  {
    id: 14,
    question: "Do you provide child seats or booster seats?",
    answer: "Yes, we can provide child seats and booster seats on request. Please mention this requirement while booking so we can arrange the appropriate safety equipment for your little ones.",
    category: "Services",
  },
  {
    id: 15,
    question: "Can I book a taxi for multiple days?",
    answer: "Absolutely! We offer multi-day packages for outstation trips, pilgrimages, and tours. You can book our vehicles for as many days as needed. Multi-day bookings come with discounted daily rates.",
    category: "Booking",
  },
  {
    id: 16,
    question: "What is the distance from Delhi to Vrindavan?",
    answer: "The distance from Delhi to Vrindavan is approximately 180 km and takes about 4-5 hours by road, depending on traffic conditions. We offer comfortable taxi service for this route with experienced drivers.",
    category: "Routes",
  },
  {
    id: 17,
    question: "Do you provide tour guides for temple visits?",
    answer: "Yes, we can arrange professional tour guides who are knowledgeable about the history, mythology, and spiritual significance of temples in Mathura, Vrindavan, and surrounding areas. Guide service is included in most tour packages.",
    category: "Services",
  },
  {
    id: 18,
    question: "Are your prices fixed or negotiable?",
    answer: "Our prices are transparent and fixed based on distance, vehicle type, and package inclusions. We don't believe in hidden charges or last-minute surprises. However, we do offer seasonal discounts and special offers from time to time.",
    category: "Pricing",
  },
  {
    id: 19,
    question: "Do you provide taxi service for senior citizens?",
    answer: "Yes, we specialize in providing comfortable and safe transportation for senior citizens. Our drivers are trained to assist elderly passengers, and we can arrange vehicles with easier entry/exit. We prioritize comfort and safety for senior travelers.",
    category: "Services",
  },
  {
    id: 20,
    question: "What documents do I need to provide for booking?",
    answer: "For standard bookings, no documents are required. For airport pickups, we need flight details. For outstation trips, we may require basic ID verification. All information is kept confidential and used only for service purposes.",
    category: "Booking",
  },
  {
    id: 21,
    question: "Do you offer group travel packages?",
    answer: "Yes, we specialize in group travel with our Tempo Traveller fleet (9-26 seaters). We offer special group rates for family tours, pilgrimages, corporate outings, school trips, and wedding guest transportation.",
    category: "Services",
  },
  {
    id: 22,
    question: "Can I track my booking or driver location?",
    answer: "Yes, we provide real-time tracking for airport pickups and outstation trips. You'll receive driver details, vehicle number, and live location tracking link via SMS and WhatsApp before your trip begins.",
    category: "Services",
  },
  {
    id: 23,
    question: "What happens if the vehicle breaks down during the trip?",
    answer: "In the rare event of a vehicle breakdown, we immediately arrange a replacement vehicle from our nearest location. We have backup vehicles in all major cities. Your safety and comfort are our priority, and we ensure minimal disruption to your journey.",
    category: "Services",
  },
  {
    id: 24,
    question: "Do you provide taxi service for pilgrimage tours?",
    answer: "Yes, pilgrimage tours are our specialty. We offer comprehensive pilgrimage packages covering all major temples in Braj region including Mathura, Vrindavan, Govardhan, Barsana, Gokul, and Nandgaon. Our drivers and guides understand the spiritual significance of these destinations.",
    category: "Services",
  },
  {
    id: 25,
    question: "How far in advance should I book?",
    answer: "For local trips, same-day booking is usually available. For outstation trips, tour packages, and airport transfers, we recommend booking at least 24-48 hours in advance. During peak seasons and festivals, booking 3-7 days in advance is advisable to ensure availability.",
    category: "Booking",
  },
  {
    id: 26,
    question: "Do you offer any discounts or loyalty programs?",
    answer: "Yes, we offer various discounts including early bird discounts, repeat customer discounts, group booking discounts, and seasonal promotional offers. Join our loyalty program for exclusive deals and priority booking.",
    category: "Pricing",
  },
  {
    id: 27,
    question: "Can I make changes to my booking after confirmation?",
    answer: "Yes, you can modify your booking up to 24 hours before the trip. Changes to pickup time, location, or vehicle type can be made subject to availability. Some changes may affect the final price.",
    category: "Booking",
  },
  {
    id: 28,
    question: "Do you provide receipt or invoice for the trip?",
    answer: "Yes, we provide detailed receipts and invoices for all trips. For corporate clients, we can provide GST invoices with company details. Receipts are sent via email and can also be provided in hard copy if requested.",
    category: "Payment",
  },
];

export const BLOG_POSTS = [
  {
    id: 1,
    title: "Complete Guide to Mathura Vrindavan Temple Tour",
    slug: "complete-guide-mathura-vrindavan-temple-tour",
    excerpt: "Explore the sacred temples of Mathura and Vrindavan with our comprehensive guide. Discover the best time to visit, temple timings, and spiritual significance.",
    content: "Mathura and Vrindavan are two of the most sacred pilgrimage destinations in India...",
    image: "https://images.unsplash.com/photo-1564399580075-5dfe19c205f3?w=800",
    category: "Temple Guide",
    date: "2024-01-15",
    readTime: "8 min read",
  },
  {
    id: 2,
    title: "Best Time to Visit Vrindavan for Festivals",
    slug: "best-time-visit-vrindavan-festivals",
    excerpt: "Discover the best time to visit Vrindavan for experiencing grand festivals like Holi, Janmashtami, and Radhashtami. Plan your spiritual journey accordingly.",
    content: "Vrindavan comes alive during festivals with vibrant celebrations and divine atmosphere...",
    image: "https://images.unsplash.com/photo-1564399580075-5dfe19c205f3?w=800",
    category: "Festival Guide",
    date: "2024-01-10",
    readTime: "6 min read",
  },
  {
    id: 3,
    title: "Delhi to Vrindavan Taxi: Complete Travel Guide",
    slug: "delhi-to-vrindavan-taxi-travel-guide",
    excerpt: "Everything you need to know about traveling from Delhi to Vrindavan by taxi. Route options, travel time, best stops, and booking tips for a comfortable journey.",
    content: "The journey from Delhi to Vrindavan is a popular route for pilgrims and tourists...",
    image: "https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?w=800",
    category: "Travel Guide",
    date: "2024-01-05",
    readTime: "5 min read",
  },
  {
    id: 4,
    title: "Govardhan Parikrama: A Spiritual Journey",
    slug: "govardhan-parikrama-spiritual-journey",
    excerpt: "Learn about the sacred Govardhan Parikrama, its spiritual significance, route details, and tips for completing this divine circumambulation.",
    content: "Govardhan Parikrama is one of the most sacred pilgrimages in the Braj region...",
    image: "https://images.unsplash.com/photo-1564399580075-5dfe19c205f3?w=800",
    category: "Temple Guide",
    date: "2023-12-28",
    readTime: "7 min read",
  },
  {
    id: 5,
    title: "Choosing the Right Vehicle for Your Trip",
    slug: "choosing-right-vehicle-trip",
    excerpt: "A comprehensive guide to selecting the perfect vehicle for your journey - from sedans to tempo travellers. Compare options based on group size, budget, and comfort.",
    content: "Selecting the right vehicle is crucial for a comfortable travel experience...",
    image: "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=800",
    category: "Taxi Guide",
    date: "2023-12-20",
    readTime: "6 min read",
  },
  {
    id: 6,
    title: "Prem Mandir Vrindavan: A Complete Visitor Guide",
    slug: "prem-mandir-vrindavan-visitor-guide",
    excerpt: "Discover the magnificent Prem Mandir in Vrindavan. Learn about its history, architecture, best visiting times, and what makes it a must-visit destination.",
    content: "Prem Mandir is one of the most beautiful temples in Vrindavan...",
    image: "https://images.unsplash.com/photo-1564399580075-5dfe19c205f3?w=800",
    category: "Temple Guide",
    date: "2023-12-15",
    readTime: "5 min read",
  },
];

export const GALLERY_IMAGES = [
  {
    id: 1,
    src: "https://images.unsplash.com/photo-1564399580075-5dfe19c205f3?w=800",
    alt: "Prem Mandir Vrindavan",
    category: "Temples",
  },
  {
    id: 2,
    src: "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=800",
    alt: "Luxury Taxi Fleet",
    category: "Fleet",
  },
  {
    id: 3,
    src: "https://images.unsplash.com/photo-1564507592333-c60657eea523?w=800",
    alt: "Taj Mahal Agra",
    category: "Destinations",
  },
  {
    id: 4,
    src: "https://images.unsplash.com/photo-1570125909232-eb263c188f7e?w=800",
    alt: "Tempo Traveller",
    category: "Fleet",
  },
  {
    id: 5,
    src: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800",
    alt: "Luxury Sedan",
    category: "Fleet",
  },
  {
    id: 6,
    src: "https://images.unsplash.com/photo-1550355291-bbee04a92027?w=800",
    alt: "SUV Vehicle",
    category: "Fleet",
  },
  {
    id: 7,
    src: "https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?w=800",
    alt: "Road Journey",
    category: "Travel",
  },
  {
    id: 8,
    src: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800",
    alt: "Happy Customer",
    category: "Customers",
  },
  {
    id: 9,
    src: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=800",
    alt: "Family Tour",
    category: "Customers",
  },
  {
    id: 10,
    src: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=800",
    alt: "Pilgrimage Tour",
    category: "Travel",
  },
  {
    id: 11,
    src: "https://images.unsplash.com/photo-1564399580075-5dfe19c205f3?w=800",
    alt: "ISKCON Temple",
    category: "Temples",
  },
  {
    id: 12,
    src: "https://images.unsplash.com/photo-1564399580075-5dfe19c205f3?w=800",
    alt: "Yamuna River",
    category: "Destinations",
  },
];

export const STATISTICS = [
  { id: 1, value: 5000, label: "Happy Customers", suffix: "+" },
  { id: 2, value: 15, label: "Years Experience", suffix: "+" },
  { id: 3, value: 50, label: "Vehicles", suffix: "+" },
  { id: 4, value: 100, label: "Cities Covered", suffix: "+" },
  { id: 5, value: 25, label: "Tour Packages", suffix: "+" },
  { id: 6, value: 98, label: "Satisfaction Rate", suffix: "%" },
];
